                                       Numpy And Pandas For Data Science

1-First import numpy library

In [180]:
import numpy as np  #np is alias will be used for numpy(shortform)

2-Create a 1-D array in numpy

In [166]:
one_d=np.arange(10) #from 0 to 9 (10 not included)
one_d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
list=[1,2,3,4,5]
list_to_array=np.array(list)
print(list_to_array)
print(type(list_to_array))

#or can do directly
list_to_array=np.array([1,2,3,4,5])
print(list_to_array)

#To get shape
print(list_to_array.shape)

#to get data type
print(list_to_array.dtype)

#to get dimension
print(list_to_array.ndim)

#to get special values in array
zeros_array=np.zeros(10) #all values will be 0
print(zeros_array)
print(zeros_array.dtype)
ones_array=np.ones(10) # all values will be 1
print(ones_array)
print(ones_array.dtype)

#to get a special dtpe array
a=np.arange(10,dtype=np.float32)
print(a)
b=np.array([1,2.5,3.4,6,7],dtype=np.int32) #values can be truncated when changing datatype
print(b)
c=b.astype(a.dtype)#astype used to change datatype
print(c)
print(c.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)
int32
1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1 2 3 6 7]
[1. 2. 3. 6. 7.]
float32


3-Mathematical operation on 1-D array

In [168]:
array=np.arange(5)
print(array*10)
print(array/10)

#operation b/w two 1-D array (only when both array have same dimensions)
#all operation will be element-wise in 1-D array
first=np.array([2,3,4])
second=np.array([3,7,8])
third=np.array([9,8]) # first(second) third can't be added due to different dimebsions i.e, (3,) and (2,)
print(first+second)
print(first-second)
print(first*second)
print(first/second) 

#operation with same array
print(first+first)
#print(first+third) this will give error

[ 0 10 20 30 40]

[0.  0.1 0.2 0.3 0.4]

[ 5 10 12]

[-1 -4 -4]

[ 6 21 32]

[0.66666667 0.42857143 0.5       ]

[4 6 8]


In [169]:
array=np.arange(10)
print(array)
print(np.sum(array))
print(np.sqrt(array)) #for square root
print(np.exp(array)) #for exponential
print(np.mean(array)) #for finding mean

[0 1 2 3 4 5 6 7 8 9]

45

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]

4.5


4-Indexing and Slicing in 1-D

In [170]:
array=np.arange(10)
print(array)

#simple indexing
print(array[3])
array[3]=90
print(array)

#we can also use negative slicing
array=np.arange(10)
print(array)
print(array[-1]) #it starts from the end with -1 goes to -10
print(array[-7])
array[-5]=70
print(array)

#slicing
array=np.arange(10)
print(array[5:8]) #last index will not be included, (5,6,7) will be included
array[5:8]=0 #can change values of array
print(array)
array[5:8]=np.nan #null type values inserting
print(array)
sliced_array=array[0:3] #it's view not copy of array, means any changes in this array will be reflected in original array
sliced_array[0]=100
print(sliced_array,"\n")
print(array,"\n")

#to tackle this use copy, any changes in this wil;l not be reflected in original array
sliced_array=array[0:3].copy()
sliced_array[0]=200
print(sliced_array,"\n")
print(array)

#negative indexing
print("negative indexing")
array=np.arange(10)
print(array[-6:-1])  #ame as positive slicing and -1 will not be included(till -6 to -2) 



[0 1 2 3 4 5 6 7 8 9]

3

[ 0  1  2 90  4  5  6  7  8  9]

[0 1 2 3 4 5 6 7 8 9]

9

3

[ 0  1  2  3  4 70  6  7  8  9]

[5 6 7]

[0 1 2 3 4 0 0 0 8 9]

[          0           1           2           3           4 -2147483648
 -2147483648 -2147483648           8           9]

[100   1   2] 


[        100           1           2           3           4 -2147483648
 -2147483648 -2147483648           8           9] 

[200   1   2] 

[        100           1           2           3           4 -2147483648
 -2147483648 -2147483648           8           9]
negative indexing
[4 5 6 7 8]


5-Create a 2-D array in Numpy (also called matrix)

In [171]:
#from a 2D list
two_d_list=[[1,2],[3,4],[5,6]]
two_d_array=np.array(two_d_list)
print(two_d_array)
print("Shape=",two_d_array.shape)
a=np.array([[1,2],[3,4],[5,6]]) #directly
print(a)

#generating random no.s with random function
two_d_array=np.random.randn(3,4) # (3,4) are dimensions i.e, no. of rows=3, no.of columns=4
print(two_d_array)
print(two_d_array.shape)
print(two_d_array.dtype)
print(two_d_array.ndim)

#also can generate in a range with right dimensions
two_d_range=np.arange(12).reshape(3,4)
print(two_d_range)
print(two_d_array.shape)
print(two_d_array.dtype)
print(two_d_array.ndim)

#You can't make two_d_range=np.arange(14).reshape(3,4) because 14 values can't be boxed in (3,4) matrix,only 12 12(3X4)

#two_d_range=np.arange(10).reshape(3,4) thiw will also produce error only 12 can contain 
zeros_2d=np.zeros((2,3))
print(zeros_2d)
ones_2d=np.ones((2,3))
print(ones_2d)



[[1 2]
 [3 4]
 [5 6]]
Shape= (3, 2)

[[1 2]
 [3 4]
 [5 6]]

[[ 1.13162939  1.51981682  2.18557541 -1.39649634]
 [-1.44411381 -0.50446586  0.16003707  0.87616892]
 [ 0.31563495 -2.02220122 -0.30620401  0.82797464]]

(3, 4)

float64

2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

(3, 4)

float64

2

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]


6-Mathematical Operations on 2-D

In [172]:
#any type of operation will be performrd on whole matrix
two_d_array=np.arange(12).reshape(3,4)
print(two_d_array)
new=two_d_array*10
print(new)
new=two_d_array+10
print(new)
#for 2 dimensions calculations, the shape of both vectors should be same
first=np.array([[1,2],[3,4],[5,6]])
second=np.array([[4,5],[6,7],[8,9]])
print("Sum= \n",first+second) #operation happens element_wise with same location
print("Square of whole array \n",first**2)
print(np.sum(first))
print(np.sqrt(first))
print(np.exp(first))
print(np.mean(first))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Sum= 
 [[ 5  7]
 [ 9 11]
 [13 15]]
Square of whole array 
 [[ 1  4]
 [ 9 16]
 [25 36]]
21
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]
3.5


7-Indexing and Slicing in 2D arrays

In [173]:
#indexing
arr2d=np.arange(12).reshape(3,4)
print(arr2d)
print(arr2d[1]) #it will slice that particular row 
print(arr2d[2][0]) #it mean 3 row and 1 column (get a particular element)
print(arr2d[-1])
#slicing
print("Slicing \n")
new=arr2d[:] # : means selecting whole arrray
print(new)
new[:]=10 #giving same value to array i.e, 10
print(new,arr2d) #but arr2d also changes, same concept as 1-d, we will use copy

arr2d=np.arange(12).reshape(3,4)

new=arr2d[:].copy() # : means copying whole arrray
print(new)
new[:]=10 #giving same value to array i.e, 10
print(new,"\n",arr2d) #only new changes not arr2d

#selecting both rows and column in once
print(arr2d[:2])#only first two arrays
print(arr2d[:,2]) #it means all rows but only 3 column
print(arr2d[0:1,1:3])#it means selecting 1 column but only 2 and 3 column
arr2d[0:1,1:3]=100 #edit same as 1D 
print(arr2d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
8
[ 8  9 10 11]
Slicing 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]
[ 2  6 10]
[[1 2]]
[[  0 100 100   3]
 [  4   5   6   7]
 [  8   9  10  11]]


8-Boolean Indexing in 1D and 2D

In boolean indexing, only those rows appears which are true or which have values 1 and 0 or false get discarde.  

In [174]:
#In 1D
array=np.array([3,4,5,6,4,8,4])
print(array)
boolean=(array==4) #boolean array which is true only where value is 4 
print(boolean)
new=np.arange(7)
print(new)
filter=new[boolean] #boolean array and new array should be of same length
print(filter)

#In 2D
print("In 2D")
arr2d=np.arange(28).reshape(7,4)
print(arr2d)
print(boolean) #same boolen arrray as above
filter=arr2d[boolean] #the rows in arr2d and no. of elements in boolean are equal
print(filter)

#reverse the condition or boolean array by ~ sign
print(boolean)
print(~boolean)
print(arr2d[~boolean])


[3 4 5 6 4 8 4]
[False  True False False  True False  True]
[0 1 2 3 4 5 6]
[1 4 6]
In 2D
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True False False  True False  True]
[[ 4  5  6  7]
 [16 17 18 19]
 [24 25 26 27]]
[False  True False False  True False  True]
[ True False  True  True False  True False]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]


9-Some conditioning filtering in 1D and 2D arrays

In [175]:
#In 1D
arr1d=np.arange(10)
print(arr1d)
new=arr1d[arr1d>4]
print(new)
#whenever you compare any array in numpy it always makes a boolean array
print(arr1d>4) #same as boolean indexing, but this time not any boolean arrray but only the original array and applying condition
print(arr1d[arr1d==2])
#we can merge two condition by and(&) or Or (|)
mask=(arr1d>5)& (arr1d<10) #and operation b/w both boolean arrays
print(mask)
print(arr1d[mask]) #can also assign the value
arr1d[arr1d<5]=0 #no.s less than 5 will be 0
print(arr1d)
#In 2D
print("In 2D")
#it happens same like boolean indexing
names=["Arun","Saushu","Niggu","Pinju","Arun","Niggu","Lapo"]
name_array=np.array(names)
arr2d=np.arange(21).reshape(7,3)
print(arr2d)
mask=(name_array=="Arun") | (name_array=="Niggu")
print(mask)
print(arr2d[mask])
print(arr2d[~mask]) # ~ for reversing th condition


[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[False False False False False  True  True  True  True  True]
[2]
[False False False False False False  True  True  True  True]
[6 7 8 9]
[0 0 0 0 0 5 6 7 8 9]
In 2D
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
[ True False  True False  True  True False]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [15 16 17]]
[[ 3  4  5]
 [ 9 10 11]
 [18 19 20]]


10-Fancy Indexing in 2D arrays

In [176]:
arr2d=np.arange(50).reshape(10,5)
print(arr2d)
print(arr2d[[3,7,1,0,9]])#pass a list of rows, and rows will be appearing in order given
print(arr2d[[2,6,4,5],[0,3,0,2]]) #first list is rows and other is respective columns(always give 1D array as an asnswer)
#we can also use negative indexing here
print(arr2d[[-4,-2,-6]])
print(arr2d[[-4,-2,-6],[-2,-4,-1]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[15 16 17 18 19]
 [35 36 37 38 39]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [45 46 47 48 49]]
[10 33 20 27]
[[30 31 32 33 34]
 [40 41 42 43 44]
 [20 21 22 23 24]]
[33 41 24]


11-Statistical Function For Data Science

In [177]:
#Transpose an array
np.random.seed(1)
array=np.random.randn(5,4)
print(array)
print(array.shape)
print(array.T) #trasnpose
#mean of 2-D array
arr=np.arange(15).reshape(5,3)
print(arr)
print(np.mean(arr))
print(np.mean(arr,axis=1))# 1 means you have to traverse columns for every row, 0 means travese every row for columns
print(np.mean(arr,axis=0)) #this technique also used for np.sum()
#dot product
print("Dot")
first=np.random.randn(3,4)
second=np.random.randn(4,3)
dot=np.dot(first,second)
print(dot)
print(first@second) #also can use @ to do dot product
#where function
array=np.arange(10).reshape(5,2)
print(array)
new=np.where(array>5,0,-9) #if condition is true then place 0 , otherwise -9 and it is a copy not a view.
print(new)
#if don't want other condition then
new=np.where(array>5,0,array)
print(new)

    


[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]
 [ 0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127]
 [-0.17242821 -0.87785842  0.04221375  0.58281521]]
(5, 4)
[[ 1.62434536  0.86540763  0.3190391  -0.3224172  -0.17242821]
 [-0.61175641 -2.3015387  -0.24937038 -0.38405435 -0.87785842]
 [-0.52817175  1.74481176  1.46210794  1.13376944  0.04221375]
 [-1.07296862 -0.7612069  -2.06014071 -1.09989127  0.58281521]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
7.0
[ 1.  4.  7. 10. 13.]
[6. 7. 8.]
Dot
[[ 1.7922517  -0.05518479  1.68461927]
 [ 0.01625811  0.6105056  -2.32514518]
 [-0.61848146 -0.58295627 -0.23465973]]
[[ 1.7922517  -0.05518479  1.68461927]
 [ 0.01625811  0.6105056  -2.32514518]
 [-0.61848146 -0.58295627 -0.23465973]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[-9 -9]
 [-9 -9]
 [-9 -9]
 [ 0  0]
 [ 0  0]]
[[0 1]
 [2 3]
 [4 5]
 [0 0]
 [0 0]]


12-Sorting in 1-D and 2-D

In [178]:
#In 1D
arr=np.random.randn(10)
print(arr)
print(np.sort(arr))
#In 2D
print("in 2D")
arr=np.random.randn(3,4)
print(arr)
print(np.sort(arr))#defaultly sort inside all rows
print(np.sort(arr,axis=0))
#Unique functions
arr=np.array([2,3,4,3,5,6,7,6,56,2,78])
print(np.unique(arr)) #Unique= sorted sets

mask=np.in1d(arr,[2,4,7]) #True for only given list for given array
print(mask)


[ 0.05080775 -0.63699565  0.19091548  2.10025514  0.12015895  0.61720311
  0.30017032 -0.35224985 -1.1425182  -0.34934272]
[-1.1425182  -0.63699565 -0.35224985 -0.34934272  0.05080775  0.12015895
  0.19091548  0.30017032  0.61720311  2.10025514]
in 2D
[[-0.20889423  0.58662319  0.83898341  0.93110208]
 [ 0.28558733  0.88514116 -0.75439794  1.25286816]
 [ 0.51292982 -0.29809284  0.48851815 -0.07557171]]
[[-0.20889423  0.58662319  0.83898341  0.93110208]
 [-0.75439794  0.28558733  0.88514116  1.25286816]
 [-0.29809284 -0.07557171  0.48851815  0.51292982]]
[[-0.20889423 -0.29809284 -0.75439794 -0.07557171]
 [ 0.28558733  0.58662319  0.48851815  0.93110208]
 [ 0.51292982  0.88514116  0.83898341  1.25286816]]
[ 2  3  4  5  6  7 56 78]
[ True False  True False False False  True False False  True False]


13-Saving and Loading in Numpy

In [179]:
#it can save any dimension array in .npy format
arr=np.arange(10)
np.save("saved",arr) #it saves arrray in .npy file
loaded=np.load("saved.npy")
print(loaded)

[0 1 2 3 4 5 6 7 8 9]
